### ISSUE TITLE
Question on updates

### ISSUE THREAD

**Issue by skiano** [learningequality/vue-intl#10]
If you use switch locales with ```Vue.setLocale``` from a user action, will all the components that use ```$format*``` methods update with the new locale?

**Comment by rtibbles** [comment]
Hi @skiano sorry for the delay here, never saw the ping for this.

The locale value should change, but as they are methods, they would need to be called again in order for the translated text to render again.

Ideally, it would be nice if the whole flow was reactive, and changing the locale immediately rerendered any translated messages - but this would require more development of component based messages, rather than relying on the methods.

**Comment by skiano** [comment]
thanks for the info!

**Comment by rtibbles** [comment]
We are archiving this repository in favour of the FormatJS integrated vue-intl plugin: https://github.com/formatjs/formatjs
