### ISSUE TITLE
Problems and broken docu

### ISSUE THREAD

**Issue by GELight** [learningequality/vue-intl#18]
Hi,

Sorry, when my issue here is not sooo detailed but its easier so read my written post in the vue forum.
https://forum.vuejs.org/t/problems-with-internationalization-with-vue-intl/39930

I hope hope hope hope .... you can give me related vue examples  for my 3 problems.

Best regards,
Mario

**Comment by rtibbles** [comment]
Hi @GELight - apologies, for some reason I have stopped getting notifications from this repository, so had not seen your issue.

I note from the forum post that you have been recommended to use vue-i18n instead.

I think the issue that you were encountering was due to your nested message structure, similar to the issue here: #14 and was fixed here: #24 which I will release soon.

Apologies for not getting back to you sooner!

**Comment by rtibbles** [comment]
We are archiving this repository in favour of the FormatJS integrated vue-intl plugin: https://github.com/formatjs/formatjs
