### ISSUE TITLE
Setting a new locale not reactive

### ISSUE THREAD

**Issue by idshdx** [learningequality/vue-intl#21]
Hi.

Setting a new locale does not trigger a rerender on components. Any way to do this?
Example:
````
(Vue as any).prototype.$http.get('http://localhost:3001/api/locale/fr-FR')
        .then( (data) => {
          (Vue as any).registerMessages(data.lang, data.labels);
          (Vue as any).setLocale('data.lang');
.....
````
When I change pages, the correct translations appear but thats not desired in a reactive workflow.
I have tried using $nextTick, nothing.
I have tried using $forceUpdate, but it rerenders only the current component instance where I am running the code, not child component instances. 

Am I doing something wrong or its broken?

Using current latest 2.1.1 version

Edit:

I have managed to trigger an component update with this workaround:
````
.then( (response) => {
            (Vue as any).registerMessages(response.data.language, response.data.labels);
            (Vue as any).setLocale(response.data.language);
            this.$emit('set-language', response.data.language);
````
In the app container component where I define child components:
````
<template>
  <el-container v-if="!this.rerender">
    <Header v-on:set-language="setLanguageRerender($event)"></Header>
    <el-main>
      <router-view />
    </el-main>
  </el-container>
</template>
....
data() {
      return {
        rerender: false
      };
    },
.....
setLanguageRerender($event) {
        this.rerender = true;
        this.$nextTick( function() {
          this.rerender= false;
        });
      },
.....
````

**Comment by rtibbles** [comment]
This is not currently supported, no - it might be possible but would require making the locale tracker a reactive object, and then that might allow Vue to know to re-call the format methods on the strings when it changes, but also not sure whether the Vue reactivity would pick up on it.

**Comment by averri** [comment]
This is a very usfeful library. The ICU message support is a standard way for adding internationalization support for applications.

I think this is a crucial feature. If the locale property is not reactive, the usability will suffer because it will require a full page refresh after setting a new locale.

The lack of reactivity is a blocker for using this library.

**Comment by rtibbles** [comment]
Thanks for the feedback, @averri - in our use of it, a full page refresh has been a prerequisite (because we have been using it in the context of Django). I think using `Vue.observable` would allow this to be accomplished much more easily now, but would limit support to Vue versions that support this.

**Comment by averri** [comment]
Thanks for the info @rtibbles.

**Comment by rtibbles** [comment]
We are archiving this repository in favour of the FormatJS integrated vue-intl plugin: https://github.com/formatjs/formatjs
